spring:
  application:
    name: Krolchansk
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:sqlite:/data/krolchansk.db
    username: postgres
    password: password
    driver-class-name: org.sqlite.JDBC
  flyway:
    url: jdbc:sqlite:/data/krolchansk.db
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
    min-response-size: 2048