spring:
  application:
    name: Krolchansk
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:sqlite:data/krolchansk.db
    username: postgres
    password: password
    driver-class-name: org.sqlite.JDBC
  flyway:
    url: jdbc:sqlite:data/krolchansk.db
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true

springdoc:
  swagger-ui:
    csrf:
      enabled: false

admin:
  password: $2a$12$aolOaYy2pOBBYQIc0K4C2uJshhh5yx9.EO41z2vdFKGP.dkUOMk8.

url:
  yandex: https://smartcaptcha.yandexcloud.net

captcha:
  key: ysc1_YaDiVwUIQg3EX0J6xy5Bce7fw6bcM69J9SkGtwJsc11fe86d
  secret: ysc2_YaDiVwUIQg3EX0J6xy5BCEbV1AXXiwkXliFocbhI2b74db84

logging:
  level:
    org:
      springframework:
        security=DEBUG:

server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
    min-response-size: 2048